### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by Teuf94420** [kasperlaursen/octoprint-card#14]
I 've try to install your interresting card , following steps dscribed in the installation section . But i can't get any result . The js file is well loaded , I get the blus frame of your card , but all information, included the image SVG are replaced by 'undefined . 
thanks for your help

**Comment by Teuf94420** [comment]
![Capture d’écran 2021-05-13 180258](https://user-images.githubusercontent.com/70345209/118152878-809cba80-b415-11eb-8f12-5808b3df4785.png)
don't know why the blue color change with the screen capture

**Comment by kasperlaursen** [comment]
Hi @Teuf94420, 
Sorry for the late answer, been a busy few weeks. 

Lets start with a few basic questions and see if it includes a solution:

Have you installed the [Home Assistant Octoprint integration](https://www.home-assistant.io/integrations/octoprint/)?  
That is needed to get the required sensors for display in the card. 

**If yes**
How does your configuration look for the Lovelace component? - Is it an exact copy of my example?
If you navigate to `{you Hass address}/config/entities` do you find the entities with the names from your config?

**About the image**
The image needs to be uploaded somewhere manually.
The imageUrl in the config is what defines where Hass will look for the image. 
In my example the file is called `printer.svg` ans is located on my Hass machine under the path `config/www`

I hope some of this helps you get the card up and running. 
If not please let me know and I'll try to support you further!

**Comment by Teuf94420** [comment]
Hi, thanks for your response . 
octoprint integration works fine with my actual setup , i got temperature for the tool and the bed, time elapsed and remaining and the camera (as you can see in the image below octoprint.png) . 

![octoprint](https://user-images.githubusercontent.com/70345209/120032124-02860980-bffa-11eb-84f9-c6a7d9b95078.png)

Next , my config for your card is : 
type: 'custom:octoprint-card'
bedActual: sensor.cr_x_actual_bed_temp
bedTarget: sensor.cr_x_target_bed_temp
toolActual: sensor.cr_x_actual_tool0_temp
toolTarget: sensor.cr_x_target_tool0_temp
currentState: sensor.cr_x_current_state
timeElapsed: sensor.cr_x_time_elapsed
timeRemaining: ssensor.cr_x_time_remaining
jobPercentage: sensor.cr_x_job_percentage
printing: binary_sensor.cr_x_printing
imageUrl: /local/media/3dprinter1.svg
videoSource: camera.cr_x
octoPrintUrl: 'http://192.168.1.90/'

images are stored in www/media/ and called them in Ha with local/media 

with all that , i get always the same result with octoprint-card
![octoprint-card](https://user-images.githubusercontent.com/70345209/120032563-a7a0e200-bffa-11eb-8528-f0abf17ef4ad.png)

**Comment by kasperlaursen** [comment]
Thanks for the extra details @Teuf94420 🙂
I think I found the problem, there's an extra s in one of your sensor names 😄

```diff
- timeRemaining: ssensor.cr_x_time_remaining
+ timeRemaining: sensor.cr_x_time_remaining
```

I really need to add some better error handling to the component, so that such a small error does not kill everything 😅

**Comment by Teuf94420** [comment]
thanks it's work !

**Comment by kasperlaursen** [comment]
Great! Hope you'll be happy with the component! 
If you have any idea feel free to at them as issues with the label "Feature Request" 🙂
